name: Build

on:
  push:
    branches: [ main ]
    tags: [ v* ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: 0 0 * * */5

jobs:
  build:
    runs-on: ubuntu-latest
    container: schunit/schunit:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run SchUnit
        run: schunit -r